#%RAML 0.8
title: Google Sheets API Hook
version: 1.0
baseUri: https://spreadsheets.google.com/feeds
securedBy: [oauth_2_0]
securitySchemes:
- oauth_2_0:
    description: |
            Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Do not use
            with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
            Used to send a valid OAuth 2 access token. Do not use together with
            the "Authorization" header
          type: string
      responses:
        401:
          description: |
            Bad or expired token. This can happen if the user or Dropbox
            revoked or expired an access token. To fix, you should re-
            authenticate the user.
        403:
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired
            imestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
      authorizationUri: https://accounts.google.com/o/oauth2/auth
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
/spreadsheets/{visibility}/{protection}:
  get:
    description: <<get a list of spreadsheets that are owned by the caller. Only visibility of "private" and protection of "full" is allowed on this resource>>
    responses:
      200:
        body:
          application/atom+xml:
            example: |
                <feed xmlns="http://www.w3.org/2005/Atom" xmlns:openSearch="http://a9.com/-/spec/opensearchrss/1.0/">
                  <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full</id>
                  <updated>2015-01-16T05:40:13.379Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">Available Spreadsheets - paulpog@japarasolutions.com</title>
                  <link rel="alternate" type="text/html" href="http://docs.google.com" />
                  <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full" />
                  <openSearch:totalResults>5</openSearch:totalResults>
                  <openSearch:startIndex>1</openSearch:startIndex>
                  <entry>
                  <id>
                  https://spreadsheets.google.com/feeds/spreadsheets/private/full/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo
                  </id>
                  <updated>2015-01-16T04:29:58.834Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">Hello World</title>
                  <content type="text">Hello World</content>
                  <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full" />
                  <link rel="alternate" type="text/html" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/edit" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo" />
                  <author>
                  <name>paulpog</name>
                  <email>paulpog@japarasolutions.com</email>
                  </author>
                  </entry>
                  <entry>
                  <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/tbu-6zoUX4V6XWmJBQeQvzA</id>
                  <updated>2013-01-12T20:55:43.466Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">January 11 2013 ProServe Engagement</title>
                  <content type="text">January 11 2013 ProServe Engagement</content>
                  <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/tbu-6zoUX4V6XWmJBQeQvzA/private/values" />
                  <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0AgKrVCbAmqO9dGJ1LTZ6b1VYNFY2WFdtSkJRZVF2ekE" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/tbu-6zoUX4V6XWmJBQeQvzA" />
                  <author>
                  <name>96redpony</name>
                  <email>96redpony@gmail.com</email>
                  </author>
                  </entry>
                  <entry>
                  <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8SNhinY21OC6eJTGQlpQxA</id>
                  <updated>2012-12-20T07:20:58.796Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">API test results</title>
                  <content type="text">API test results</content>
                  <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/t8SNhinY21OC6eJTGQlpQxA/private/full" />
                  <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0AltuRm_7iT6CdDhTTmhpblkyMU9DNmVKVEdRbHBReEE" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8SNhinY21OC6eJTGQlpQxA" />
                  <author>
                  <name>cynthia.qiao</name>
                  <email>cynthia.qiao@gmail.com</email>
                  </author>
                  </entry>
                  <entry>
                  <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/tBeNp6xXYNK4LFle9fIv-tA</id>
                  <updated>2012-10-22T07:16:26.002Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">Custell Development Testing Log</title>
                  <content type="text">Custell Development Testing Log</content>
                  <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/tBeNp6xXYNK4LFle9fIv-tA/private/full" />
                  <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0Aptp56nRSLhvdEJlTnA2eFhZTks0TEZsZTlmSXYtdEE" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/tBeNp6xXYNK4LFle9fIv-tA" />
                  <author>
                  <name>john.smibert</name>
                  <email>john.smibert@gmail.com</email>
                  </author>
                  </entry>
                  <entry>
                  <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8tSsj__33gyUM1vJnsfE7A</id>
                  <updated>2011-12-10T06:02:29.461Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                  <title type="text">Custell Performace Testing</title>
                  <content type="text">Custell Performace Testing</content>
                  <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/t8tSsj__33gyUM1vJnsfE7A/private/full" />
                  <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0Aptp56nRSLhvdDh0U3NqX18zM2d5VU0xdkpuc2ZFN0E" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8tSsj__33gyUM1vJnsfE7A" />
                  <author>
                  <name>john.smibert</name>
                  <email>john.smibert@gmail.com</email>
                  </author>
                  </entry>
                </feed>
  /{key}:
    get:
      description: <<get a spreadsheet that is defined by the {key}. Only visibility of "private" and protection of "full" is allowed on this resource>>
      responses:
        200:
          body:
            application/atom+xml:
              example: |
                  <feed xmlns="http://www.w3.org/2005/Atom" xmlns:openSearch="http://a9.com/-/spec/opensearchrss/1.0/">
                    <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full</id>
                    <updated>2015-01-16T05:40:13.379Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">Available Spreadsheets - paulpog@japarasolutions.com</title>
                    <link rel="alternate" type="text/html" href="http://docs.google.com" />
                    <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full" />
                    <openSearch:totalResults>5</openSearch:totalResults>
                    <openSearch:startIndex>1</openSearch:startIndex>
                    <entry>
                    <id>
                    https://spreadsheets.google.com/feeds/spreadsheets/private/full/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo
                    </id>
                    <updated>2015-01-16T04:29:58.834Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">Hello World</title>
                    <content type="text">Hello World</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full" />
                    <link rel="alternate" type="text/html" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/edit" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo" />
                    <author>
                    <name>paulpog</name>
                    <email>paulpog@japarasolutions.com</email>
                    </author>
                    </entry>
                    <entry>
                    <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/tbu-6zoUX4V6XWmJBQeQvzA</id>
                    <updated>2013-01-12T20:55:43.466Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">January 11 2013 ProServe Engagement</title>
                    <content type="text">January 11 2013 ProServe Engagement</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/tbu-6zoUX4V6XWmJBQeQvzA/private/values" />
                    <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0AgKrVCbAmqO9dGJ1LTZ6b1VYNFY2WFdtSkJRZVF2ekE" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/tbu-6zoUX4V6XWmJBQeQvzA" />
                    <author>
                    <name>96redpony</name>
                    <email>96redpony@gmail.com</email>
                    </author>
                    </entry>
                    <entry>
                    <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8SNhinY21OC6eJTGQlpQxA</id>
                    <updated>2012-12-20T07:20:58.796Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">API test results</title>
                    <content type="text">API test results</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/t8SNhinY21OC6eJTGQlpQxA/private/full" />
                    <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0AltuRm_7iT6CdDhTTmhpblkyMU9DNmVKVEdRbHBReEE" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8SNhinY21OC6eJTGQlpQxA" />
                    <author>
                    <name>cynthia.qiao</name>
                    <email>cynthia.qiao@gmail.com</email>
                    </author>
                    </entry>
                    <entry>
                    <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/tBeNp6xXYNK4LFle9fIv-tA</id>
                    <updated>2012-10-22T07:16:26.002Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">Custell Development Testing Log</title>
                    <content type="text">Custell Development Testing Log</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/tBeNp6xXYNK4LFle9fIv-tA/private/full" />
                    <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0Aptp56nRSLhvdEJlTnA2eFhZTks0TEZsZTlmSXYtdEE" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/tBeNp6xXYNK4LFle9fIv-tA" />
                    <author>
                    <name>john.smibert</name>
                    <email>john.smibert@gmail.com</email>
                    </author>
                    </entry>
                    <entry>
                    <id>https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8tSsj__33gyUM1vJnsfE7A</id>
                    <updated>2011-12-10T06:02:29.461Z</updated>
                    <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#spreadsheet" />
                    <title type="text">Custell Performace Testing</title>
                    <content type="text">Custell Performace Testing</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#worksheetsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/t8tSsj__33gyUM1vJnsfE7A/private/full" />
                    <link rel="alternate" type="text/html" href="https://spreadsheets.google.com/ccc?key=0Aptp56nRSLhvdDh0U3NqX18zM2d5VU0xdkpuc2ZFN0E" />
                    <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/spreadsheets/private/full/t8tSsj__33gyUM1vJnsfE7A" />
                    <author>
                    <name>john.smibert</name>
                    <email>john.smibert@gmail.com</email>
                    </author>
                    </entry>
                  </feed>
/worksheets/{key}/{visibility}/{protection}:
  get:
    description: <<request a list of worksheets in a given spreadsheet, issue a GET request to that URL, with an appropriate authorization header. The Key is retreived from the "link" element that has rel="http://schemas.google.com/spreadsheets/2006#tablesfeed" in the apparopriate "entry" element from the GET spreadsheet list response. That element's href value provides the URL for that spreadsheet's worksheets feed. >>
    responses:
      200:
        body:
          application/atom+xml:
            example: |
                <feed xmlns="http://www.w3.org/2005/Atom"
                  xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
                  xmlns:gs="http://schemas.google.com/spreadsheets/2006"
                  xmlns:gd="http://schemas.google.com/g/2005"
                  gd:etag='W/"D0cERnk-eip7ImA9WBBXGEg."'>
                  <id>https://spreadsheets.google.com/feeds/worksheets/key/private/full</id>
                  <updated>2006-11-17T18:23:45.173Z</updated>
                  <title type="text">Groceries R Us</title>
                  <link rel="alternate" type="text/html"
                      href="https://spreadsheets.google.com/ccc?key=key"/>
                  <link rel="http://schemas.google.com/g/2005#feed"
                      type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                  <link rel="self" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                  <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                  <author>
                    <name>Fitzwilliam Darcy</name>
                    <email>fitz@gmail.com</email>
                  </author>
                  <openSearch:totalResults>1</openSearch:totalResults>
                  <openSearch:startIndex>1</openSearch:startIndex>
                  <openSearch:itemsPerPage>1</openSearch:itemsPerPage>
                  <entry gd:etag='"YDwqeyI."'>
                    <id>https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId</id>
                    <updated>2006-11-17T18:23:45.173Z</updated>
                    <title type="text">Sheet1</title>
                    <content type="text">Sheet1</content>
                    <link rel="http://schemas.google.com/spreadsheets/2006#listfeed"
                        type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/list/key/worksheetId/private/full"/>
                    <link rel="http://schemas.google.com/spreadsheets/2006#cellsfeed"
                        type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/cells/key/worksheetId/private/full"/>
                    <link rel="self" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId"/>
                    <link rel="edit" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId/version"/>
                    <gs:rowCount>100</gs:rowCount>
                    <gs:colCount>20</gs:colCount>
                  </entry>
                </feed>
  post:
    description: <<Add a Worksheet to a Spread sheet. The "key" value is the key of the spreadsheet. The Key is retreived from the "link" element that has rel="http://schemas.google.com/spreadsheets/2006#tablesfeed" in the apparopriate "entry" element from the GET spreadsheet list response. That element's href value provides the URL for that spreadsheet's worksheets feed.>>
    body:
      application/atom+xml:
        schema: |
          <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
            targetNamespace="http://www.w3.org/2005/Atom" xmlns:atom="http://www.w3.org/2005/Atom"
            xmlns:gs="http://schemas.google.com/spreadsheets/2006" vc:minVersion="1.1"
            xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
            <xs:import namespace="http://schemas.google.com/spreadsheets/2006" schemaLocation="gs.xsd"/>
            <xs:element name="entry">
              <xs:complexType>
                <xs:sequence>
                  <xs:element ref="atom:title"/>
                  <xs:element ref="gs:rowCount"/>
                  <xs:element ref="gs:colCount"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="title" type="xs:NCName"/>
          </xs:schema>
    responses:
      201:
        body:
          application/atom+xml:
            example: |
                <entry xmlns="http://www.w3.org/2005/Atom" xmlns:gs="http://schemas.google.com/spreadsheets/2006" xmlns:gd="http://schemas.google.com/g/2005" gd:etag=""IRxeEE0cCit7ImA."">
                  <id>
                  https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi
                  </id>
                  <updated>2015-01-16T04:29:02.539Z</updated>
                  <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-16T04:29:02.539Z</app:edited>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#worksheet" />
                  <title>Expenses</title>
                  <content type="application/atom+xml;type=feed" src="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full" />
                  <link rel="http://schemas.google.com/spreadsheets/2006#cellsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/cells/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full" />
                  <link rel="http://schemas.google.com/visualization/2008#visualizationApi" type="application/atom+xml" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/gviz/tq?gid=2135548936" />
                  <link rel="http://schemas.google.com/spreadsheets/2006#exportcsv" type="text/csv" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/export?gid=2135548936&format=csv" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full/ozbg8gi" />
                  <link rel="edit" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full/ozbg8gi" />
                  <gs:colCount>10</gs:colCount>
                  <gs:rowCount>50</gs:rowCount>
                </entry>
  put:
    description: <<modify the title and size of a worksheet in a Spreadsheet. To change the title or size of a worksheet, begin by getting the desired worksheet from the worksheet feed. Then update the worksheet's metadata. The URL to use is teh value of the href attribute of the link element that has the attribute of rel="edit" from the get worksheet call>>
    body:
      application/atom+xml:
        schema: |
          <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:app="http://www.w3.org/2007/app" xmlns:gs="http://schemas.google.com/spreadsheets/2006">
            <xs:import namespace="http://schemas.google.com/spreadsheets/2006" schemaLocation="gs.xsd"/>
            <xs:import namespace="http://www.w3.org/2007/app" schemaLocation="app.xsd"/>
            <xs:element name="entry">
              <xs:complexType>
                <xs:sequence>
                  <xs:element ref="id"/>
                  <xs:element ref="updated"/>
                  <xs:element ref="app:edited"/>
                  <xs:element ref="category"/>
                  <xs:element ref="title"/>
                  <xs:element ref="content"/>
                  <xs:element maxOccurs="unbounded" ref="link"/>
                  <xs:element ref="gs:colCount"/>
                  <xs:element ref="gs:rowCount"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="id" type="xs:anyURI"/>
            <xs:element name="updated" type="xs:dateTime"/>
            <xs:element name="category">
              <xs:complexType>
                <xs:attribute name="scheme" use="required" type="xs:anyURI"/>
                <xs:attribute name="term" use="required" type="xs:anyURI"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="title" type="xs:NCName"/>
            <xs:element name="content">
              <xs:complexType>
                <xs:attribute name="src" use="required" type="xs:anyURI"/>
                <xs:attribute name="type" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="link">
              <xs:complexType>
                <xs:attribute name="href" use="required" type="xs:anyURI"/>
                <xs:attribute name="rel" use="required" type="xs:anyURI"/>
                <xs:attribute name="type" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:schema>
    responses:
      201:
        body:
          application/atom+xml:
            example: |
                <entry xmlns="http://www.w3.org/2005/Atom" xmlns:gs="http://schemas.google.com/spreadsheets/2006" xmlns:gd="http://schemas.google.com/g/2005" gd:etag=""IRxeEE0cCit7ImA."">
                  <id>
                  https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi
                  </id>
                  <updated>2015-01-16T04:29:02.539Z</updated>
                  <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-16T04:29:02.539Z</app:edited>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#worksheet" />
                  <title>Income</title>
                  <content type="application/atom+xml;type=feed" src="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full" />
                  <link rel="http://schemas.google.com/spreadsheets/2006#cellsfeed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/cells/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full" />
                  <link rel="http://schemas.google.com/visualization/2008#visualizationApi" type="application/atom+xml" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/gviz/tq?gid=2135548936" />
                  <link rel="http://schemas.google.com/spreadsheets/2006#exportcsv" type="text/csv" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/export?gid=2135548936&format=csv" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full/ozbg8gi" />
                  <link rel="edit" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/worksheets/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/private/full/ozbg8gi" />
                  <gs:colCount>10</gs:colCount>
                  <gs:rowCount>50</gs:rowCount>
                </entry>
  delete:
    description: <<Delete a worksheet in a Spreadsheet. The URL to use is the value of the href attribute of the link element that has the attribute of rel="edit" from the get worksheet call>>
  /{worksheetid}:
    get:
      description: <<request a worksheet in a given spreadsheet, issue a GET request to that URL, with an appropriate authorization header. The Key is retreived from the "link" element that has rel="http://schemas.google.com/spreadsheets/2006#tablesfeed" in the apparopriate "entry" element from the GET spreadsheet list response. That element's href value provides the URL for that spreadsheet's worksheets feed. >>
      responses:
        200:
          body:
            application/atom+xml:
              example: |
                  <feed xmlns="http://www.w3.org/2005/Atom"
                    xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
                    xmlns:gs="http://schemas.google.com/spreadsheets/2006"
                    xmlns:gd="http://schemas.google.com/g/2005"
                    gd:etag='W/"D0cERnk-eip7ImA9WBBXGEg."'>
                    <id>https://spreadsheets.google.com/feeds/worksheets/key/private/full</id>
                    <updated>2006-11-17T18:23:45.173Z</updated>
                    <title type="text">Groceries R Us</title>
                    <link rel="alternate" type="text/html"
                        href="https://spreadsheets.google.com/ccc?key=key"/>
                    <link rel="http://schemas.google.com/g/2005#feed"
                        type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                    <link rel="self" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                    <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/worksheets/key/private/full"/>
                    <author>
                      <name>Fitzwilliam Darcy</name>
                      <email>fitz@gmail.com</email>
                    </author>
                    <openSearch:totalResults>1</openSearch:totalResults>
                    <openSearch:startIndex>1</openSearch:startIndex>
                    <openSearch:itemsPerPage>1</openSearch:itemsPerPage>
                    <entry gd:etag='"YDwqeyI."'>
                      <id>https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId</id>
                      <updated>2006-11-17T18:23:45.173Z</updated>
                      <title type="text">Sheet1</title>
                      <content type="text">Sheet1</content>
                      <link rel="http://schemas.google.com/spreadsheets/2006#listfeed"
                          type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/list/key/worksheetId/private/full"/>
                      <link rel="http://schemas.google.com/spreadsheets/2006#cellsfeed"
                          type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/cells/key/worksheetId/private/full"/>
                      <link rel="self" type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId"/>
                      <link rel="edit" type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheetId/version"/>
                      <gs:rowCount>100</gs:rowCount>
                      <gs:colCount>20</gs:colCount>
                    </entry>
                  </feed>
/list/{key}/{worksheetId}/{visibility}/{protection}:
  get:
    description: <<Get the list of Rows in the worksheet. The list feed contains all rows after the first row up to the first blank row.>>
    queryParameters:
      reverse:
        type: boolean
        required: false
        description: To get rows in reverse order, send the following request, using the reverse query parameter to specify the sort order.
      orderby:
        type: string
        pattern: column:lastname
        required: false
        description: To sort the values in ascending order by a particular column, rather than by row number, use the orderby query parameter. The column name used in the orderby parameter is case sensitive and must match the name of the column as it appears in the API. The column names are the header values of the worksheet lowercased and with all non-alpha-numeric characters removed. For example, if the cell A1 contains the value "Time 2 Eat!" the column name would be "time2eat".
      sq:
        type: string
        required: false
        description: Use the structured query parameter sq to produce a feed with entries that meet the specified criteria. To find all people in a worksheet older than 25 years, with a height less than 175cm, one would use the query - sq=age>25%20and%20height<175
    responses:
      200:
        body:
          application/atom+xml:
            example: |
                <feed xmlns="http://www.w3.org/2005/Atom" xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended" xmlns:gd="http://schemas.google.com/g/2005" gd:etag="W/"DU4HR38ycSt7ImA9XRRSFUg."">
                  <id>
                  https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full
                  </id>
                  <updated>2015-01-18T05:12:16.199Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#list" />
                  <title>Hello World</title>
                  <link rel="alternate" type="application/atom+xml" href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/edit" />
                  <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full" />
                  <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full" />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full" />
                  <author>
                  <name>paulpog</name>
                  <email>paulpog@japarasolutions.com</email>
                  </author>
                  <openSearch:totalResults>1</openSearch:totalResults>
                  <openSearch:startIndexopenSearch:startIndex>1</openSearch:startIndex>
                  <entry gd:etag=""NFBNB0QaVCt7ImA."">
                  <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/cokwr</id>
                  <updated>2015-01-18T05:12:16.199Z</updated>
                  <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-18T05:12:16.199Z</app:edited>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#list" />
                  <title>Hello World</title>
                  <content />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full/cokwr" />
                  <link rel="edit" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/od6/private/full/cokwr" />
                  <gsx:helloworld>Hello World</gsx:helloworld>
                  </entry>
                </feed>
  post:
    description: <<Adding rows to a worksheet via the list feed involves specifying values for each column in the worksheet, and sending this row representation to the API. Then determine the appropriate URL to send the entry to, known as the POST URL. You can find the POST URL in the list feed's link element that has rel="http://schemas.google.com/g/2005#post".>>
    body:
      application/atom+xml:
        schema: |
          <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3.org/2005/Atom" xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended" xmlns:atom="http://www.w3.org/2005/Atom">
            <xs:import namespace="http://schemas.google.com/spreadsheets/2006/extended" schemaLocation="gsx.xsd"/>
            <xs:element name="entry">
              <xs:complexType>
                <xs:sequence>
                  <xs:element ref="gsx:hours"/>
                  <xs:element ref="gsx:ipm"/>
                  <xs:element ref="gsx:items"/>
                  <xs:element ref="gsx:name"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:schema>
    responses:
      200:
        body:
          application/atom+xml:
  put:
    description: <<modify a row in the worksheet>>
    body:
      application/atom+xml:
        schema: |
          <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
            targetNamespace="http://www.w3.org/2005/Atom"
            xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended"
            xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gd="http://schemas.google.com/g/2005"
            vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
            <xs:import namespace="http://schemas.google.com/g/2005" schemaLocation="gd.xsd"/>
            <xs:import namespace="http://schemas.google.com/spreadsheets/2006/extended"
              schemaLocation="gsx.xsd"/>
            <xs:element name="entry">
              <xs:complexType>
                <xs:sequence>
                  <xs:element ref="atom:id"/>
                  <xs:element ref="atom:updated"/>
                  <xs:element ref="atom:category"/>
                  <xs:element ref="atom:title"/>
                  <xs:element ref="atom:content"/>
                  <xs:element maxOccurs="unbounded" ref="atom:link"/>
                  <xs:element ref="gsx:name"/>
                  <xs:element ref="gsx:hours"/>
                  <xs:element ref="gsx:items"/>
                  <xs:element ref="gsx:ipm"/>
                </xs:sequence>
                <xs:attribute ref="gd:etag" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="id" type="xs:anyURI"/>
            <xs:element name="updated" type="xs:dateTime"/>
            <xs:element name="category">
              <xs:complexType>
                <xs:attribute name="scheme" use="required" type="xs:anyURI"/>
                <xs:attribute name="term" use="required" type="xs:anyURI"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="title">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:NCName">
                    <xs:attribute name="type" use="required" type="xs:NCName"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
            <xs:element name="content">
              <xs:complexType mixed="true">
                <xs:attribute name="type" use="required" type="xs:NCName"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="link">
              <xs:complexType>
                <xs:attribute name="href" use="required" type="xs:anyURI"/>
                <xs:attribute name="rel" use="required" type="xs:NCName"/>
                <xs:attribute name="type" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:schema>
    responses:
      200:
        body:
          application/atom+xml:
            example: |
                <entry xmlns="http://www.w3.org/2005/Atom" xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended" xmlns:gd="http://schemas.google.com/g/2005" gd:etag=""NAgWCBZFWCt7ImA."">
                  <id>
                  https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/cokwr
                  </id>
                  <updated>2015-01-19T00:48:02.719Z</updated>
                  <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-19T00:48:02.719Z</app:edited>
                  <category scheme="http://schemas.google.com/spreadsheets/2006" term="http://schemas.google.com/spreadsheets/2006#list" />
                  <title>Hello WOrld</title>
                  <content />
                  <link rel="self" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr" />
                  <link rel="edit" type="application/atom+xml" href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr" />
                  <gsx:helloworld>Hello WOrld</gsx:helloworld>
                </entry>
  delete:
    description: <<To delete a row, first retrieve the row to delete, then send a DELETE request to the row's edit URL. This is the same URL used to update the row.>>
    responses:
      200:
      
/cells/{key}/{worksheetId}/{visibility}/{protection}:
  description:  In a cell feed, each entry represents a single cell. Cells are referred to by position.
                 There are two positioning notations used in Google Sheets. The first, called A1 notation, uses characters from the Latin alphabet to indicate the column, and integers to indicate the row of a cell. The second, called R1C1 notation, uses integers to represent both the column and the row, and precedes each by a corresponding R or C, to indicate row or column number. The addresses A1 and R1C1 are equivalent, as are the addresses B5 and R5C2.
                   Cell ranges also have notations in Google Sheets, but those are less relevant here.
                   Formulas often refer to other cells or cell ranges by their position. The cells feed allows formulas to be set on cells. However, the API always returns cell addresses for formulas on cells in R1C1 notation, even if the formula was set with A1 notation.
                   The title of a cell entry is always the A1 position of the cell.
                   The id URI of a cell entry always contains the R1C1 position of the cell.
                   The inputValue attribute of a cell entry always contains the value that a user would otherwise type into the Google Sheets user interface to manipulate the cell (i.e. either a literal value or a formula). To set a formula or a literal value on a cell, provide the text of the formula or value as the inputValue attribute. Remember that formulas must start with = to be considered a formula. If a cell contains a formula, the formula is always provided as the inputValue when cell entries are returned by the API.
                   The numericValue attribute of a cell entry, when present, indicates that the cell was determined to have a numeric value, and its numeric value is indicated with this attributed.
                   The literal value of the cell element is the calculated value of the cell, without formatting applied. If the cell contains a formula, the calculated value is given here. The Sheets API has no concept of formatting, and thus cannot manipulate formatting of cells.
  get:
    description: <<get a cell. To determine the URL of a cell feed for a given worksheet, get the worksheets feed and examine the link element in which rel is http://schemas.google.com/spreadsheets/2006#cellsfeed. The href value in that element is the cell feed's URI.>>
    queryParameters:
      min-row:
        type: string
        required: false
      max-row:
        type: string
        required: false
      min-col:
        type: string
        required: false
      max-col:
        type: string
        required: false
    responses:
      200:
        body:
          application/atom+xml:
            example: |
              <feed xmlns="http://www.w3.org/2005/Atom" xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
                xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended"
                xmlns:gd="http://schemas.google.com/g/2005" gd:etag="W/&quot;C0UCQ3g4eSt7ImA9XRRSFk4.&quot;">
                <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full</id>
                <updated>2015-01-19T01:34:22.631Z</updated>
                <category scheme="http://schemas.google.com/spreadsheets/2006"
                    term="http://schemas.google.com/spreadsheets/2006#list"/>
                <title>Expenses</title>
                <link rel="alternate" type="application/atom+xml"
                    href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/edit"/>
                <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml"
                    href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml"
                    href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                <link rel="self" type="application/atom+xml"
                    href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                <author>
                    <name>paulpog</name>
                    <email>paulpog@japarasolutions.com</email>
                </author>
                <openSearch:totalResults>1</openSearch:totalResults>
                <openSearch:startIndex>1</openSearch:startIndex>
                <entry gd:etag="&quot;NFBNB0QaVCt7ImA.&quot;">
                    <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/cokwr</id>
                    <updated>2015-01-19T01:34:22.631Z</updated>
                    <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-19T01:34:22.631Z</app:edited>
                    <category scheme="http://schemas.google.com/spreadsheets/2006"
                        term="http://schemas.google.com/spreadsheets/2006#list"/>
                    <title>Hello World</title>
                    <content/>
                    <link rel="self" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                    <link rel="edit" type="application/atom+xml"
                        href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                    <gsx:helloworld>Hello World</gsx:helloworld>
                </entry>
              </feed>
  put:
    description: <<Cells can be modified in place. Unlike other feeds, cells are not directly added nor deleted. They are fixed in place, based on the dimensions of a given worksheet. To add or remove cells from a worksheet, use the worksheets feed to change the dimension of the worksheet. To empty a cell, simply update its value to be an empty string. Use HTTP PUT to change the data in a cell, even if it is empty; the use of POST on empty cells is no longer recommended. To clear a cell, send an entry with an empty content element in your PUT request instead of using DELETE.>>
    body:
      application/atom+xml:
        schema: |
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3.org/2005/Atom" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gs="http://schemas.google.com/spreadsheets/2006">
              <xs:import namespace="http://schemas.google.com/spreadsheets/2006" schemaLocation="gs.xsd"/>
              <xs:element name="entry">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="atom:id"/>
                    <xs:element ref="atom:link"/>
                    <xs:element ref="gs:cell"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="id" type="xs:anyURI"/>
              <xs:element name="link">
                <xs:complexType>
                  <xs:attribute name="href" use="required" type="xs:anyURI"/>
                  <xs:attribute name="rel" use="required" type="xs:NCName"/>
                  <xs:attribute name="type" use="required"/>
                </xs:complexType>
              </xs:element>
    responses:
      200:
        body:
          application/atom+xml:
            example: |
              <entry xmlns="http://www.w3.org/2005/Atom"
                xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended"
                xmlns:gd="http://schemas.google.com/g/2005" gd:etag="&quot;NAgQD00WXyt7ImA.&quot;">
                <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/cokwr</id>
                <updated>2015-01-19T01:34:22.631Z</updated>
                <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-19T01:34:22.631Z</app:edited>
                <category scheme="http://schemas.google.com/spreadsheets/2006"
                    term="http://schemas.google.com/spreadsheets/2006#list"/>
                <title>Hello W0rld</title>
                <content/>
                <link rel="self" type="application/atom+xml"
                    href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                <link rel="edit" type="application/atom+xml"
                    href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                <gsx:helloworld>Hello W0rld</gsx:helloworld>
              </entry>
  /{cellId}:
    description:  Manipulate an individual Cell. The cellId is in the R1C1 format. Note that this means the 'R' and the 'C' MUST be in CAPITALS
    get:
      description: <<get a cell. To determine the URL of a cell feed for a given worksheet, get the worksheets feed and examine the link element in which rel is http://schemas.google.com/spreadsheets/2006#cellsfeed. The href value in that element is the cell feed's URI.>>
      responses:
        200:
          body:
            application/atom+xml:
              example: |
                <feed xmlns="http://www.w3.org/2005/Atom" xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
                  xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended"
                  xmlns:gd="http://schemas.google.com/g/2005" gd:etag="W/&quot;C0UCQ3g4eSt7ImA9XRRSFk4.&quot;">
                  <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full</id>
                  <updated>2015-01-19T01:34:22.631Z</updated>
                  <category scheme="http://schemas.google.com/spreadsheets/2006"
                      term="http://schemas.google.com/spreadsheets/2006#list"/>
                  <title>Expenses</title>
                  <link rel="alternate" type="application/atom+xml"
                      href="https://docs.google.com/a/japarasolutions.com/spreadsheets/d/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/edit"/>
                  <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                  <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                  <link rel="self" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full"/>
                  <author>
                      <name>paulpog</name>
                      <email>paulpog@japarasolutions.com</email>
                  </author>
                  <openSearch:totalResults>1</openSearch:totalResults>
                  <openSearch:startIndex>1</openSearch:startIndex>
                  <entry gd:etag="&quot;NFBNB0QaVCt7ImA.&quot;">
                      <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/cokwr</id>
                      <updated>2015-01-19T01:34:22.631Z</updated>
                      <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-19T01:34:22.631Z</app:edited>
                      <category scheme="http://schemas.google.com/spreadsheets/2006"
                          term="http://schemas.google.com/spreadsheets/2006#list"/>
                      <title>Hello World</title>
                      <content/>
                      <link rel="self" type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                      <link rel="edit" type="application/atom+xml"
                          href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                      <gsx:helloworld>Hello World</gsx:helloworld>
                  </entry>
                </feed>
    put:
      description: <<Cells can be modified in place. Unlike other feeds, cells are not directly added nor deleted. They are fixed in place, based on the dimensions of a given worksheet. To add or remove cells from a worksheet, use the worksheets feed to change the dimension of the worksheet. To empty a cell, simply update its value to be an empty string. Use HTTP PUT to change the data in a cell, even if it is empty; the use of POST on empty cells is no longer recommended. To clear a cell, send an entry with an empty content element in your PUT request instead of using DELETE.>>
      body:
        application/atom+xml:
          schema: |
              <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3.org/2005/Atom" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gs="http://schemas.google.com/spreadsheets/2006">
                <xs:import namespace="http://schemas.google.com/spreadsheets/2006" schemaLocation="gs.xsd"/>
                <xs:element name="entry">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element ref="atom:id"/>
                      <xs:element ref="atom:link"/>
                      <xs:element ref="gs:cell"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="id" type="xs:anyURI"/>
                <xs:element name="link">
                  <xs:complexType>
                    <xs:attribute name="href" use="required" type="xs:anyURI"/>
                    <xs:attribute name="rel" use="required" type="xs:NCName"/>
                    <xs:attribute name="type" use="required"/>
                  </xs:complexType>
                </xs:element>
      responses:
        200:
          body:
            application/atom+xml:
              example: |
                <entry xmlns="http://www.w3.org/2005/Atom"
                  xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended"
                  xmlns:gd="http://schemas.google.com/g/2005" gd:etag="&quot;NAgQD00WXyt7ImA.&quot;">
                  <id>https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/cokwr</id>
                  <updated>2015-01-19T01:34:22.631Z</updated>
                  <app:edited xmlns:app="http://www.w3.org/2007/app">2015-01-19T01:34:22.631Z</app:edited>
                  <category scheme="http://schemas.google.com/spreadsheets/2006"
                      term="http://schemas.google.com/spreadsheets/2006#list"/>
                  <title>Hello W0rld</title>
                  <content/>
                  <link rel="self" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                  <link rel="edit" type="application/atom+xml"
                      href="https://spreadsheets.google.com/feeds/list/1XCaYpVdLm-XGnvaVeL9VtN9ywA7Ewr_3RL1t5TvOeFo/ozbg8gi/private/full/cokwr"/>
                  <gsx:helloworld>Hello W0rld</gsx:helloworld>
                </entry>
  /batch:
    description:  The API supports updating an entire column, row, or other set of cells, in a single request.     This is offered to improve performance over making large sets of individual requests. This process is            called "batching requests".
        Important - Only the cells feed supports batching requests.
        A number of batch operations can be combined into a single request. The two types of batch operations supported are query and update. insert and delete are not supported because the cells feed cannot be used to insert or delete cells. Remember that the worksheets feed must be used to do that. 
        query and update can be combined in any size set, and sent to the API in a single request. The API responds with information on the status of each individual operation within the batch. For query requests, the result is the requested cell. For update requests, the result includes the manipulated cell with new values.
    post:
      description: <<Begin by creating a cells feed and setting the feed id to the href value of the post link.   Then, append all the entries to be updated to the feed as per the XML shown below and set the batch:operation to update. Finally, send the XML using a POST request to the cells feed batch link.
        Each cell entry element appended to the feed element must contain the following elements....
        batch:id 
        A batch:id element, uniquely identifying each individual cell update within the batch update request. For best results, set this value to some local identifier, so that the response can be identified once retrieved.
        batch:operation
        A batch:operation element, whose type attribute determines the type of request to be performed (query or update).
        id
        An id element containing the full URL to the cell to be updated. Be sure to examine the output XML when requesting the cells feed for more details.
        link
        A link element whose rel attribute is set to edit. The link's type attribute must be set to application/atom+xml and the href attribute must contain the full path to the cell's id. Refer to the contents of the cells feed for more details.
        gs:cell
        A gs:cell element, whose row attribute corresponds to the row being updated, whose col attribute corresponds to the column being updated and whose inputValue attribute contains the same information as the value of the content element discussed above, or the new formula for the cell.>>
      body:
        application/atom+xml:
          schema: |
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3.org/2005/Atom" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gs="http://schemas.google.com/spreadsheets/2006"
              xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
              <xs:import namespace="http://schemas.google.com/spreadsheets/2006" schemaLocation="gs.xsd"/>
              <xs:element name="entry">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="atom:id"/>
                    <xs:element ref="atom:link"/>
                    <xs:element ref="gs:cell"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="id" type="xs:anyURI"/>
              <xs:element name="link">
                <xs:complexType>
                  <xs:attribute name="href" use="required" type="xs:anyURI"/>
                  <xs:attribute name="rel" use="required" type="xs:NCName"/>
                  <xs:attribute name="type" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:schema>
/helloworld:
  get:
    description: <<returns all spreadsheets on your google drive>>
    responses:
      200:
        body:
          application/atom+xml: